name: Publish npm package and deploy docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd src && npm i

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: cd src && npm i
      - run: cd src && npm run build
      - run: cd src && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISHING_TOKEN }}

  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Allow writing to GitHub Pages branch
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: cd docs && npm install
      - name: Build VitePress site
        run: cd docs && npm run docs:build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist